version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: goldencommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  auth-service:
    build: ./auth-service  # ← String correto, caminho pasta torre guarda (não true/false)
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/goldencommerce
      SECRET_KEY: mysecretkey123
      ALGORITHM: HS256
    depends_on:
      - postgres
  product-service:
    build: ./product-service  # ← String correto, caminho pasta torre loja (não true/false)
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/goldencommerce
    depends_on:
      - postgres
volumes:
  pgdata:
  mongodb_data: